kind: Service
apiVersion: v1
metadata:
  name: ruby-service
spec:
  selector:
    app: google-cloud-demo
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
